import { Facility, Review } from './types';

export const MOCK_FACILITIES: Facility[] = [
  {
    id: '1',
    name: '新宿ワークプレイス',
    description: '新宿駅から徒歩3分の好立地。静かな集中エリアと、通話可能なカフェエリアが分かれています。',
    address: '東京都新宿区新宿3-1-1',
    prefecture: '東京都',
    city: '新宿区',
    area: '新宿',
    nearestStation: '新宿駅',
    walkMinutes: 3,
    priceInfo: '1時間 500円〜',
    businessHours: '09:00 - 22:00',
    hasDropIn: true,
    canCall: true,
    hasPrivateRoom: true,
    seatTypes: ['オープンデスク', '個室', 'ソファ席'],
    hasPower: true,
    hasWifi: true,
    quietnessLevel: 4,
    isBusinessInquiryAvailable: true,
    images: ['https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&q=80&w=800'],
    status: 'published',
    isFeatured: true,
    sponsoredRank: 0,
    averageRating: 4.5,
    reviewCount: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '2',
    name: '渋谷クリエイティブベース',
    description: 'クリエイター向けの開放的な空間。高速Wi-Fi完備で、動画編集やデザイン作業に最適。',
    address: '東京都渋谷区渋谷2-1-1',
    prefecture: '東京都',
    city: '渋谷区',
    area: '渋谷',
    nearestStation: '渋谷駅',
    walkMinutes: 5,
    priceInfo: '1時間 600円〜',
    businessHours: '10:00 - 21:00',
    hasDropIn: true,
    canCall: true,
    hasPrivateRoom: false,
    seatTypes: ['オープンデスク', 'カウンター席'],
    hasPower: true,
    hasWifi: true,
    quietnessLevel: 3,
    isBusinessInquiryAvailable: true,
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800'],
    status: 'published',
    isFeatured: false,
    sponsoredRank: 0,
    averageRating: 4.2,
    reviewCount: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    facilityId: '1',
    userId: 'u1',
    userName: '田中 太郎',
    userRole: 'worker',
    rating: 5,
    quietnessRating: 5,
    callEaseRating: 4,
    facilitySatisfactionRating: 5,
    comment: 'とても静かで集中できました。駅からも近くて便利です。',
    createdAt: Date.now() - 86400000,
  }
];
